INFO 2024-11-28 19:15:53,380 tasks Starting stock price updater...
INFO 2024-11-28 19:15:53,382 tasks Stock price updater started
INFO 2024-11-28 19:15:54,864 tasks Starting stock price updater...
INFO 2024-11-28 19:15:54,865 tasks Stock price updater started
INFO 2024-11-28 19:15:54,883 autoreload Watching for file changes with StatReloader
ERROR 2024-11-28 19:15:58,358 log Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        template_name,
        ^^^^^^^^^^^^^^
        skip=history,
        ^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\template\engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\mazam\Desktop\stockwatch\core\views.py", line 13, in dashboard
    return render(request, 'core/dashboard.html', {'stocks': stocks})
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\template\backends\django.py", line 109, in render
    reraise(exc, self.backend)
    ~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\template\backends\django.py", line 130, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
ERROR 2024-11-28 19:15:58,364 basehttp "GET / HTTP/1.1" 500 128488
INFO 2024-11-28 19:17:20,145 tasks Starting stock price updater...
INFO 2024-11-28 19:17:20,147 tasks Stock price updater started
INFO 2024-11-28 19:17:21,356 tasks Starting stock price updater...
INFO 2024-11-28 19:17:21,358 tasks Stock price updater started
INFO 2024-11-28 19:17:21,377 autoreload Watching for file changes with StatReloader
ERROR 2024-11-28 19:17:24,073 log Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        template_name,
        ^^^^^^^^^^^^^^
        skip=history,
        ^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\template\engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\mazam\Desktop\stockwatch\core\views.py", line 13, in dashboard
    return render(request, 'core/dashboard.html', {'stocks': stocks})
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\template\backends\django.py", line 109, in render
    reraise(exc, self.backend)
    ~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\template\backends\django.py", line 130, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
ERROR 2024-11-28 19:17:24,081 basehttp "GET / HTTP/1.1" 500 128488
INFO 2024-11-28 19:17:36,078 tasks Starting stock price updater...
INFO 2024-11-28 19:17:36,080 tasks Stock price updater started
INFO 2024-11-28 19:17:43,268 tasks Starting stock price updater...
INFO 2024-11-28 19:17:43,271 tasks Stock price updater started
INFO 2024-11-28 19:17:51,462 tasks Starting stock price updater...
INFO 2024-11-28 19:17:51,464 tasks Stock price updater started
INFO 2024-11-28 19:17:52,715 tasks Starting stock price updater...
INFO 2024-11-28 19:17:52,717 tasks Stock price updater started
INFO 2024-11-28 19:17:52,737 autoreload Watching for file changes with StatReloader
ERROR 2024-11-28 19:17:55,261 log Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        template_name,
        ^^^^^^^^^^^^^^
        skip=history,
        ^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\template\engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\mazam\Desktop\stockwatch\core\views.py", line 13, in dashboard
    return render(request, 'core/dashboard.html', {'stocks': stocks})
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\template\backends\django.py", line 109, in render
    reraise(exc, self.backend)
    ~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\template\backends\django.py", line 130, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
ERROR 2024-11-28 19:17:55,268 basehttp "GET / HTTP/1.1" 500 128488
INFO 2024-11-28 19:20:21,758 tasks Starting stock price updater...
INFO 2024-11-28 19:20:21,760 tasks Stock price updater started
INFO 2024-11-28 19:20:23,024 tasks Starting stock price updater...
INFO 2024-11-28 19:20:23,026 tasks Stock price updater started
INFO 2024-11-28 19:20:23,049 autoreload Watching for file changes with StatReloader
INFO 2024-11-28 19:20:25,116 basehttp "GET / HTTP/1.1" 200 5970
ERROR 2024-11-28 19:20:31,241 log Internal Server Error: /stocks/add/
Traceback (most recent call last):
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
  File "C:\Users\mazam\Desktop\stockwatch\core\views.py", line 20, in add_stock
    monitor = StockMonitor()
  File "C:\Users\mazam\Desktop\stockwatch\core\stock_monitor.py", line 15, in __init__
    self.alpha_vantage_key = settings.ALPHA_VANTAGE_API_KEY
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\conf\__init__.py", line 83, in __getattr__
    val = getattr(_wrapped, name)
AttributeError: 'Settings' object has no attribute 'ALPHA_VANTAGE_API_KEY'
ERROR 2024-11-28 19:20:31,250 basehttp "POST /stocks/add/ HTTP/1.1" 500 79632
ERROR 2024-11-28 19:20:33,026 log Internal Server Error: /stocks/add/
Traceback (most recent call last):
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
  File "C:\Users\mazam\Desktop\stockwatch\core\views.py", line 20, in add_stock
    monitor = StockMonitor()
  File "C:\Users\mazam\Desktop\stockwatch\core\stock_monitor.py", line 15, in __init__
    self.alpha_vantage_key = settings.ALPHA_VANTAGE_API_KEY
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\conf\__init__.py", line 83, in __getattr__
    val = getattr(_wrapped, name)
AttributeError: 'Settings' object has no attribute 'ALPHA_VANTAGE_API_KEY'
ERROR 2024-11-28 19:20:33,033 basehttp "POST /stocks/add/ HTTP/1.1" 500 79632
ERROR 2024-11-28 19:20:33,184 log Internal Server Error: /stocks/add/
Traceback (most recent call last):
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
  File "C:\Users\mazam\Desktop\stockwatch\core\views.py", line 20, in add_stock
    monitor = StockMonitor()
  File "C:\Users\mazam\Desktop\stockwatch\core\stock_monitor.py", line 15, in __init__
    self.alpha_vantage_key = settings.ALPHA_VANTAGE_API_KEY
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\conf\__init__.py", line 83, in __getattr__
    val = getattr(_wrapped, name)
AttributeError: 'Settings' object has no attribute 'ALPHA_VANTAGE_API_KEY'
ERROR 2024-11-28 19:20:33,191 basehttp "POST /stocks/add/ HTTP/1.1" 500 79632
ERROR 2024-11-28 19:20:33,325 log Internal Server Error: /stocks/add/
Traceback (most recent call last):
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
  File "C:\Users\mazam\Desktop\stockwatch\core\views.py", line 20, in add_stock
    monitor = StockMonitor()
  File "C:\Users\mazam\Desktop\stockwatch\core\stock_monitor.py", line 15, in __init__
    self.alpha_vantage_key = settings.ALPHA_VANTAGE_API_KEY
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\conf\__init__.py", line 83, in __getattr__
    val = getattr(_wrapped, name)
AttributeError: 'Settings' object has no attribute 'ALPHA_VANTAGE_API_KEY'
ERROR 2024-11-28 19:20:33,332 basehttp "POST /stocks/add/ HTTP/1.1" 500 79632
ERROR 2024-11-28 19:21:26,259 log Internal Server Error: /stocks/check/
Traceback (most recent call last):
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\mazam\Desktop\stockwatch\core\views.py", line 49, in check_prices
    monitor = StockMonitor()
  File "C:\Users\mazam\Desktop\stockwatch\core\stock_monitor.py", line 15, in __init__
    self.alpha_vantage_key = settings.ALPHA_VANTAGE_API_KEY
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\conf\__init__.py", line 83, in __getattr__
    val = getattr(_wrapped, name)
AttributeError: 'Settings' object has no attribute 'ALPHA_VANTAGE_API_KEY'
ERROR 2024-11-28 19:21:26,266 basehttp "GET /stocks/check/ HTTP/1.1" 500 74589
ERROR 2024-11-28 19:22:26,257 log Internal Server Error: /stocks/check/
Traceback (most recent call last):
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\mazam\Desktop\stockwatch\core\views.py", line 49, in check_prices
    monitor = StockMonitor()
  File "C:\Users\mazam\Desktop\stockwatch\core\stock_monitor.py", line 15, in __init__
    self.alpha_vantage_key = settings.ALPHA_VANTAGE_API_KEY
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\conf\__init__.py", line 83, in __getattr__
    val = getattr(_wrapped, name)
AttributeError: 'Settings' object has no attribute 'ALPHA_VANTAGE_API_KEY'
ERROR 2024-11-28 19:22:26,263 basehttp "GET /stocks/check/ HTTP/1.1" 500 74589
INFO 2024-11-28 19:23:13,828 autoreload C:\Users\mazam\Desktop\stockwatch\core\views.py changed, reloading.
INFO 2024-11-28 19:23:15,392 tasks Starting stock price updater...
INFO 2024-11-28 19:23:15,394 tasks Stock price updater started
INFO 2024-11-28 19:23:15,418 autoreload Watching for file changes with StatReloader
ERROR 2024-11-28 19:23:26,268 log Internal Server Error: /stocks/check/
Traceback (most recent call last):
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\mazam\Desktop\stockwatch\core\views.py", line 67, in check_prices
    monitor = StockMonitor()
  File "C:\Users\mazam\Desktop\stockwatch\core\stock_monitor.py", line 15, in __init__
    self.alpha_vantage_key = settings.ALPHA_VANTAGE_API_KEY
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\conf\__init__.py", line 83, in __getattr__
    val = getattr(_wrapped, name)
AttributeError: 'Settings' object has no attribute 'ALPHA_VANTAGE_API_KEY'
ERROR 2024-11-28 19:23:26,276 basehttp "GET /stocks/check/ HTTP/1.1" 500 74589
ERROR 2024-11-28 19:24:26,264 log Internal Server Error: /stocks/check/
Traceback (most recent call last):
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\mazam\Desktop\stockwatch\core\views.py", line 67, in check_prices
    monitor = StockMonitor()
  File "C:\Users\mazam\Desktop\stockwatch\core\stock_monitor.py", line 15, in __init__
    self.alpha_vantage_key = settings.ALPHA_VANTAGE_API_KEY
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\conf\__init__.py", line 83, in __getattr__
    val = getattr(_wrapped, name)
AttributeError: 'Settings' object has no attribute 'ALPHA_VANTAGE_API_KEY'
ERROR 2024-11-28 19:24:26,271 basehttp "GET /stocks/check/ HTTP/1.1" 500 74589
INFO 2024-11-28 19:25:04,691 autoreload C:\Users\mazam\Desktop\stockwatch\stockwatch\urls.py changed, reloading.
INFO 2024-11-28 19:25:06,337 tasks Starting stock price updater...
INFO 2024-11-28 19:25:06,338 tasks Stock price updater started
INFO 2024-11-28 19:25:06,358 autoreload Watching for file changes with StatReloader
ERROR 2024-11-28 19:26:08,277 log Internal Server Error: /stocks/check/
Traceback (most recent call last):
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\mazam\Desktop\stockwatch\core\views.py", line 67, in check_prices
    monitor = StockMonitor()
  File "C:\Users\mazam\Desktop\stockwatch\core\stock_monitor.py", line 15, in __init__
    self.alpha_vantage_key = settings.ALPHA_VANTAGE_API_KEY
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\conf\__init__.py", line 83, in __getattr__
    val = getattr(_wrapped, name)
AttributeError: 'Settings' object has no attribute 'ALPHA_VANTAGE_API_KEY'
ERROR 2024-11-28 19:26:08,285 basehttp "GET /stocks/check/ HTTP/1.1" 500 74589
ERROR 2024-11-28 19:27:08,280 log Internal Server Error: /stocks/check/
Traceback (most recent call last):
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\mazam\Desktop\stockwatch\core\views.py", line 67, in check_prices
    monitor = StockMonitor()
  File "C:\Users\mazam\Desktop\stockwatch\core\stock_monitor.py", line 15, in __init__
    self.alpha_vantage_key = settings.ALPHA_VANTAGE_API_KEY
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\conf\__init__.py", line 83, in __getattr__
    val = getattr(_wrapped, name)
AttributeError: 'Settings' object has no attribute 'ALPHA_VANTAGE_API_KEY'
ERROR 2024-11-28 19:27:08,291 basehttp "GET /stocks/check/ HTTP/1.1" 500 74589
INFO 2024-11-28 19:27:34,738 tasks Starting stock price updater...
INFO 2024-11-28 19:27:34,740 tasks Stock price updater started
INFO 2024-11-28 19:27:35,939 tasks Starting stock price updater...
INFO 2024-11-28 19:27:35,941 tasks Stock price updater started
INFO 2024-11-28 19:27:35,958 autoreload Watching for file changes with StatReloader
INFO 2024-11-28 19:28:12,328 tasks Starting stock price updater...
INFO 2024-11-28 19:28:12,329 tasks Stock price updater started
INFO 2024-11-28 19:28:13,461 tasks Starting stock price updater...
INFO 2024-11-28 19:28:13,463 tasks Stock price updater started
INFO 2024-11-28 19:28:13,479 autoreload Watching for file changes with StatReloader
ERROR 2024-11-28 19:29:08,282 log Internal Server Error: /stocks/check/
Traceback (most recent call last):
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\mazam\Desktop\stockwatch\core\views.py", line 67, in check_prices
    monitor = StockMonitor()
  File "C:\Users\mazam\Desktop\stockwatch\core\stock_monitor.py", line 15, in __init__
    self.alpha_vantage_key = settings.ALPHA_VANTAGE_API_KEY
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\conf\__init__.py", line 83, in __getattr__
    val = getattr(_wrapped, name)
AttributeError: 'Settings' object has no attribute 'ALPHA_VANTAGE_API_KEY'
ERROR 2024-11-28 19:29:08,292 basehttp "GET /stocks/check/ HTTP/1.1" 500 74589
INFO 2024-11-28 19:29:20,334 autoreload C:\Users\mazam\Desktop\stockwatch\core\tasks.py changed, reloading.
INFO 2024-11-28 19:29:22,131 tasks Starting stock price updater...
INFO 2024-11-28 19:29:22,133 tasks Stock price updater started
INFO 2024-11-28 19:29:22,155 autoreload Watching for file changes with StatReloader
INFO 2024-11-28 19:29:33,993 autoreload C:\Users\mazam\Desktop\stockwatch\core\apps.py changed, reloading.
INFO 2024-11-28 19:29:34,721 autoreload Watching for file changes with StatReloader
INFO 2024-11-28 19:29:49,713 tasks Starting stock price updater...
INFO 2024-11-28 19:29:49,715 tasks Stock price updater started
INFO 2024-11-28 19:29:50,195 autoreload Watching for file changes with StatReloader
ERROR 2024-11-28 19:30:02,853 log Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\mazam\Desktop\stockwatch\core\views.py", line 94, in landing_page
    return render(request, 'core/landing.html')
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\template\base.py", line 523, in parse
    self.unclosed_block_tag(parse_until)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\template\base.py", line 586, in unclosed_block_tag
    raise self.error(token, msg)
django.template.exceptions.TemplateSyntaxError: Unclosed tag on line 3: 'block'. Looking for one of: endblock.
ERROR 2024-11-28 19:30:02,864 basehttp "GET / HTTP/1.1" 500 168265
ERROR 2024-11-28 19:30:08,269 log Internal Server Error: /stocks/check/
Traceback (most recent call last):
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\mazam\Desktop\stockwatch\core\views.py", line 67, in check_prices
    monitor = StockMonitor()
  File "C:\Users\mazam\Desktop\stockwatch\core\stock_monitor.py", line 15, in __init__
    self.alpha_vantage_key = settings.ALPHA_VANTAGE_API_KEY
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\conf\__init__.py", line 83, in __getattr__
    val = getattr(_wrapped, name)
AttributeError: 'Settings' object has no attribute 'ALPHA_VANTAGE_API_KEY'
ERROR 2024-11-28 19:30:08,277 basehttp "GET /stocks/check/ HTTP/1.1" 500 74589
ERROR 2024-11-28 19:31:08,282 log Internal Server Error: /stocks/check/
Traceback (most recent call last):
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\mazam\Desktop\stockwatch\core\views.py", line 67, in check_prices
    monitor = StockMonitor()
  File "C:\Users\mazam\Desktop\stockwatch\core\stock_monitor.py", line 15, in __init__
    self.alpha_vantage_key = settings.ALPHA_VANTAGE_API_KEY
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\conf\__init__.py", line 83, in __getattr__
    val = getattr(_wrapped, name)
AttributeError: 'Settings' object has no attribute 'ALPHA_VANTAGE_API_KEY'
ERROR 2024-11-28 19:31:08,292 basehttp "GET /stocks/check/ HTTP/1.1" 500 74589
ERROR 2024-11-28 19:32:08,263 log Internal Server Error: /stocks/check/
Traceback (most recent call last):
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\mazam\Desktop\stockwatch\core\views.py", line 67, in check_prices
    monitor = StockMonitor()
  File "C:\Users\mazam\Desktop\stockwatch\core\stock_monitor.py", line 15, in __init__
    self.alpha_vantage_key = settings.ALPHA_VANTAGE_API_KEY
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\conf\__init__.py", line 83, in __getattr__
    val = getattr(_wrapped, name)
AttributeError: 'Settings' object has no attribute 'ALPHA_VANTAGE_API_KEY'
ERROR 2024-11-28 19:32:08,270 basehttp "GET /stocks/check/ HTTP/1.1" 500 74589
ERROR 2024-11-28 19:33:08,266 log Internal Server Error: /stocks/check/
Traceback (most recent call last):
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\mazam\Desktop\stockwatch\core\views.py", line 67, in check_prices
    monitor = StockMonitor()
  File "C:\Users\mazam\Desktop\stockwatch\core\stock_monitor.py", line 15, in __init__
    self.alpha_vantage_key = settings.ALPHA_VANTAGE_API_KEY
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\conf\__init__.py", line 83, in __getattr__
    val = getattr(_wrapped, name)
AttributeError: 'Settings' object has no attribute 'ALPHA_VANTAGE_API_KEY'
ERROR 2024-11-28 19:33:08,273 basehttp "GET /stocks/check/ HTTP/1.1" 500 74589
ERROR 2024-11-28 19:34:08,259 log Internal Server Error: /stocks/check/
Traceback (most recent call last):
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\mazam\Desktop\stockwatch\core\views.py", line 67, in check_prices
    monitor = StockMonitor()
  File "C:\Users\mazam\Desktop\stockwatch\core\stock_monitor.py", line 15, in __init__
    self.alpha_vantage_key = settings.ALPHA_VANTAGE_API_KEY
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\conf\__init__.py", line 83, in __getattr__
    val = getattr(_wrapped, name)
AttributeError: 'Settings' object has no attribute 'ALPHA_VANTAGE_API_KEY'
ERROR 2024-11-28 19:34:08,267 basehttp "GET /stocks/check/ HTTP/1.1" 500 74589
ERROR 2024-11-28 19:35:08,261 log Internal Server Error: /stocks/check/
Traceback (most recent call last):
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\mazam\Desktop\stockwatch\core\views.py", line 67, in check_prices
    monitor = StockMonitor()
  File "C:\Users\mazam\Desktop\stockwatch\core\stock_monitor.py", line 15, in __init__
    self.alpha_vantage_key = settings.ALPHA_VANTAGE_API_KEY
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\conf\__init__.py", line 83, in __getattr__
    val = getattr(_wrapped, name)
AttributeError: 'Settings' object has no attribute 'ALPHA_VANTAGE_API_KEY'
ERROR 2024-11-28 19:35:08,269 basehttp "GET /stocks/check/ HTTP/1.1" 500 74589
ERROR 2024-11-28 19:36:08,261 log Internal Server Error: /stocks/check/
Traceback (most recent call last):
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\mazam\Desktop\stockwatch\core\views.py", line 67, in check_prices
    monitor = StockMonitor()
  File "C:\Users\mazam\Desktop\stockwatch\core\stock_monitor.py", line 15, in __init__
    self.alpha_vantage_key = settings.ALPHA_VANTAGE_API_KEY
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\conf\__init__.py", line 83, in __getattr__
    val = getattr(_wrapped, name)
AttributeError: 'Settings' object has no attribute 'ALPHA_VANTAGE_API_KEY'
ERROR 2024-11-28 19:36:08,268 basehttp "GET /stocks/check/ HTTP/1.1" 500 74589
ERROR 2024-11-28 19:37:08,263 log Internal Server Error: /stocks/check/
Traceback (most recent call last):
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\mazam\Desktop\stockwatch\core\views.py", line 67, in check_prices
    monitor = StockMonitor()
  File "C:\Users\mazam\Desktop\stockwatch\core\stock_monitor.py", line 15, in __init__
    self.alpha_vantage_key = settings.ALPHA_VANTAGE_API_KEY
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mazam\Desktop\stockwatch\.venv\Lib\site-packages\django\conf\__init__.py", line 83, in __getattr__
    val = getattr(_wrapped, name)
AttributeError: 'Settings' object has no attribute 'ALPHA_VANTAGE_API_KEY'
ERROR 2024-11-28 19:37:08,270 basehttp "GET /stocks/check/ HTTP/1.1" 500 74589
INFO 2024-11-28 19:38:04,269 autoreload C:\Users\mazam\Desktop\stockwatch\core\views.py changed, reloading.
INFO 2024-11-28 19:38:05,062 autoreload Watching for file changes with StatReloader
INFO 2024-11-28 19:39:26,560 autoreload C:\Users\mazam\Desktop\stockwatch\core\views.py changed, reloading.
INFO 2024-11-28 19:39:27,218 autoreload Watching for file changes with StatReloader
INFO 2024-11-28 19:39:56,490 autoreload C:\Users\mazam\Desktop\stockwatch\core\apps.py changed, reloading.
INFO 2024-11-28 19:39:57,319 autoreload Watching for file changes with StatReloader
INFO 2024-11-28 19:40:08,253 basehttp "GET /stocks/check/ HTTP/1.1" 200 92
INFO 2024-11-28 19:40:08,272 basehttp "GET / HTTP/1.1" 200 1974
INFO 2024-11-28 19:40:11,545 autoreload C:\Users\mazam\Desktop\stockwatch\core\models.py changed, reloading.
INFO 2024-11-28 19:40:12,304 autoreload Watching for file changes with StatReloader
INFO 2024-11-28 19:40:26,012 autoreload C:\Users\mazam\Desktop\stockwatch\core\stock_monitor.py changed, reloading.
INFO 2024-11-28 19:40:26,793 autoreload Watching for file changes with StatReloader
INFO 2024-11-28 19:42:38,695 autoreload C:\Users\mazam\Desktop\stockwatch\stockwatch\settings.py changed, reloading.
INFO 2024-11-28 19:42:39,537 autoreload 9452 4300 Watching for file changes with StatReloader
INFO 2024-11-28 19:42:57,340 autoreload 9452 4300 C:\Users\mazam\Desktop\stockwatch\stockwatch\urls.py changed, reloading.
INFO 2024-11-28 19:42:58,237 autoreload 2268 8780 Watching for file changes with StatReloader
INFO 2024-11-28 19:44:55,987 tasks 7040 21568 Starting stock price updater...
INFO 2024-11-28 19:44:55,987 tasks 7040 21568 Starting stock price updater...
INFO 2024-11-28 19:44:55,989 tasks 7040 21568 Stock price updater started
INFO 2024-11-28 19:44:55,989 tasks 7040 21568 Stock price updater started
INFO 2024-11-28 19:44:56,498 autoreload 22192 4580 Watching for file changes with StatReloader
INFO 2024-11-28 19:44:59,287 basehttp 22192 23984 "GET / HTTP/1.1" 200 1974
INFO 2024-11-28 19:45:04,850 basehttp 22192 23984 "GET /dashboard/ HTTP/1.1" 200 5559
INFO 2024-11-28 19:45:08,416 basehttp 22192 23984 "POST /stocks/add/ HTTP/1.1" 200 35
INFO 2024-11-28 19:45:08,447 basehttp 22192 23984 "GET /dashboard/ HTTP/1.1" 200 8423
INFO 2024-11-28 19:45:55,993 tasks 7040 3828 Fetching info for AAPL...
INFO 2024-11-28 19:45:55,993 tasks 7040 3828 Fetching info for AAPL...
INFO 2024-11-28 19:45:56,154 tasks 7040 3828 Updated AAPL price to $0
INFO 2024-11-28 19:45:56,154 tasks 7040 3828 Updated AAPL price to $0
INFO 2024-11-28 19:46:09,282 basehttp 22192 23984 "GET /stocks/check/ HTTP/1.1" 200 21
INFO 2024-11-28 19:46:09,293 basehttp 22192 23984 "GET /dashboard/ HTTP/1.1" 200 8423
INFO 2024-11-28 19:46:58,156 tasks 7040 3828 Fetching info for AAPL...
INFO 2024-11-28 19:46:58,156 tasks 7040 3828 Fetching info for AAPL...
INFO 2024-11-28 19:46:58,204 tasks 7040 3828 Updated AAPL price to $0
INFO 2024-11-28 19:46:58,204 tasks 7040 3828 Updated AAPL price to $0
INFO 2024-11-28 19:47:10,283 basehttp 22192 23984 "GET /stocks/check/ HTTP/1.1" 200 21
INFO 2024-11-28 19:47:10,297 basehttp 22192 23984 "GET /dashboard/ HTTP/1.1" 200 8423
